micronaut:
  application:
    name: contacliencetimec
environment: Dev
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/postgres`}
    driverClassName: org.postgresql.Driver
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:pwd123}
    schema-generate: CREATE_DROP
    dialect: POSTGRES
    connectionTimeout: 2000
    initializaiont-mode: always
jpa:
  default:
    show-sql: true
    entity-scan:
      packages: 'com.example.model'
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
        generate-statistics: true
        hbm2ddl:
          auto: update
